export const blogPosts = [
  {
    id: 'math-3',
    date: '2026.05',
    tags: ['数学杂谈'],
    titleZh: '数学杂谈 — 熟悉感',
    titleEn: 'Math Musings — Familiarity',
    summaryZh: '似曾相识的公式往往让人柳暗花明又一村…把曲面面积公式里的根号看作「反投影因子」，竟是从二维推广来的普适结论',
    summaryEn: "Familiar-looking formulas often open unexpected doors… The radical in the surface area formula is an 'inverse projection factor' — a universal result generalized straight from 2D",
    sections: [
      {
        titleZh: '3.1 似曾相识的公式往往让人柳暗花明又一村…',
        titleEn: '3.1 Familiar-looking formulas often open unexpected doors…',
        contentZh: [
          { type: 'text', text: '先说发现，对于计算曲面面积的公式' },
          { type: 'math', text: 'S = \\iint_R \\sqrt{f_x^2 + f_y^2 + 1}\\, dA' },
          { type: 'text', text: '把根号下的内容看作"反投影因子"，而这竟是从二维推广来的，在正交的三维系中的普适结论' },
        ],
        contentEn: [
          { type: 'text', text: 'Start with the observation. For the surface area formula:' },
          { type: 'math', text: 'S = \\iint_R \\sqrt{f_x^2 + f_y^2 + 1}\\, dA' },
          { type: 'text', text: "Read what's under the radical as an 'inverse projection factor' — and it turns out this is generalized straight from 2D, a universal result in any orthogonal 3D coordinate system" },
        ],
      },
      {
        titleZh: '3.2 人们常说',
        titleEn: '3.2 What people usually say',
        contentZh: [
          { type: 'text', text: '老师上课一般都是这样说（呃而且是还不错的老师才会稍微讲下过程..）' },
          { type: 'text', text: 'aᵢ, bᵢ 是 x, y 方向的延申' },
          { type: 'math', text: '\\mathbf{a}_i = \\langle \\Delta x_i,\\, 0,\\, f_x\\Delta x_i \\rangle, \\quad \\mathbf{b}_i = \\langle 0,\\, \\Delta y_i,\\, f_y\\Delta y_i \\rangle' },
          { type: 'text', text: '不断微分后，两个正交的单位延申向量组成的面积就近似为曲面的面积（有点线性近似的味道）' },
          { type: 'text', text: 'so立刻想到叉积的模长，即' },
          { type: 'text', text: '从 aᵢ × bᵢ 一通化简后变成：' },
          { type: 'math', text: '\\langle -f_x,\\, -f_y,\\, 1 \\rangle\\,\\Delta x\\,\\Delta y' },
          { type: 'text', text: '然后再取模从而得到了上述公式下的一坨根号' },
          { type: 'text', text: 'over' },
        ],
        contentEn: [
          { type: 'text', text: "That's how teachers usually explain it (and only the decent ones even bother with the derivation..)" },
          { type: 'text', text: 'aᵢ, bᵢ are the extension vectors in the x, y directions' },
          { type: 'math', text: '\\mathbf{a}_i = \\langle \\Delta x_i,\\, 0,\\, f_x\\Delta x_i \\rangle, \\quad \\mathbf{b}_i = \\langle 0,\\, \\Delta y_i,\\, f_y\\Delta y_i \\rangle' },
          { type: 'text', text: 'After continuous subdivision, the area formed by two orthogonal unit extension vectors approximates the surface area (a flavor of linear approximation)' },
          { type: 'text', text: 'so you immediately think of the cross product magnitude, i.e.' },
          { type: 'text', text: 'After simplifying aᵢ × bᵢ it becomes:' },
          { type: 'math', text: '\\langle -f_x,\\, -f_y,\\, 1 \\rangle\\,\\Delta x\\,\\Delta y' },
          { type: 'text', text: 'Then take the norm and you get the pile of radicals under the formula above' },
          { type: 'text', text: 'over' },
        ],
      },
      {
        titleZh: '3.3 熟悉的 1+k²',
        titleEn: '3.3 The familiar 1+k²',
        contentZh: [
          { type: 'text', text: '很可惜本人并不满足于此，才有了这段文字' },
          { type: 'text', text: '难道没人发现 √(f²ₓ + f²ᵧ + 1) * ΔxΔy 和二维中的 √(k² + 1) * Δx 很像吗?' },
          { type: 'text', text: '二维中有：斜边 = 根号 * Δx' },
          { type: 'text', text: '翻译下是：原长度 = "反投影因子" * 投影长度' },
          { type: 'text', text: '学过三角函数的各位不难看出根号就是 1/cosθ' },
          { type: 'text', text: '那三维中有没有同样的道理呢？' },
          { type: 'quote', text: '（是否有：原曲面 = "反投影因子" * 投影面积呢？）' },
          { type: 'text', text: 'of course' },
          { type: 'text', text: '但由于坐标系的不确定，三维中的 θ 比较难一下找出来' },
          { type: 'text', text: '(thinking: 若投影与x-y共面，那理论上在平面内转x、y轴是不会影响θ的，那我们不妨找x、y轴与这个原曲面的夹角α和β吧)' },
          { type: 'text', text: '各位如果动动手画thinking部分的图，就不难发现（不画图将很难理解，但由于网站这太难放图片了，so辛苦各位了），我们其实在证：' },
          { type: 'math', text: '\\frac{1}{\\cos\\theta} = \\sqrt{k^2+1} = \\sqrt{\\tan^2\\theta+1} = \\sqrt{\\tan^2\\alpha + \\tan^2\\beta + 1}' },
          { type: 'text', text: '即证：' },
          { type: 'math', text: '\\tan^2\\theta = \\tan^2\\alpha + \\tan^2\\beta' },
          { type: 'text', text: '进一步降维分解问题，即：' },
          { type: 'text', text: '对于任何直角三角形ABC（假设直角为C），过C做AB的垂线，记C到垂足的长度为h，且a、b为角A、B的对边' },
          { type: 'text', text: '要证明：' },
          { type: 'math', text: '\\frac{1}{a^2} + \\frac{1}{b^2} = \\frac{1}{h^2}' },
          { type: 'quote', text: '而对此，高中生表示等面积+勾股就可以解决了' },
        ],
        contentEn: [
          { type: 'text', text: "I wasn't satisfied stopping there — hence this piece" },
          { type: 'text', text: "Hasn't anyone noticed that √(f²ₓ + f²ᵧ + 1) * ΔxΔy looks a lot like √(k² + 1) * Δx in 2D?" },
          { type: 'text', text: 'In 2D: hypotenuse = radical * Δx' },
          { type: 'text', text: 'Which translates to: original length = "inverse projection factor" * projected length' },
          { type: 'text', text: "Anyone who's done trig can see the radical is just 1/cosθ" },
          { type: 'text', text: 'So does the same logic hold in 3D?' },
          { type: 'quote', text: '(Is it the case that: original surface = "inverse projection factor" * projected area?)' },
          { type: 'text', text: 'of course' },
          { type: 'text', text: "But because the coordinate system is underdetermined, it's hard to pin down θ in 3D directly" },
          { type: 'text', text: "(thinking: if the projection lies in the x-y plane, rotating the x, y axes within that plane theoretically shouldn't affect θ — so let's find the angles α and β between the x, y axes and the original surface)" },
          { type: 'text', text: "If you draw the diagram for the thinking part, you'll find (it's really hard without the diagram — sorry, images are a pain to embed here) that what we're actually proving is:" },
          { type: 'math', text: '\\frac{1}{\\cos\\theta} = \\sqrt{k^2+1} = \\sqrt{\\tan^2\\theta+1} = \\sqrt{\\tan^2\\alpha + \\tan^2\\beta + 1}' },
          { type: 'text', text: 'i.e. it suffices to prove:' },
          { type: 'math', text: '\\tan^2\\theta = \\tan^2\\alpha + \\tan^2\\beta' },
          { type: 'text', text: 'Decompose the problem by reducing dimensions further:' },
          { type: 'text', text: 'For any right triangle ABC (right angle at C), drop a perpendicular from C to AB, let h be the length from C to the foot, and let a, b be the sides opposite angles A, B' },
          { type: 'text', text: 'Need to prove:' },
          { type: 'math', text: '\\frac{1}{a^2} + \\frac{1}{b^2} = \\frac{1}{h^2}' },
          { type: 'quote', text: 'And for this, a high schooler will tell you: equal area + Pythagorean theorem does it' },
        ],
      },
      {
        titleZh: '3.4 感受？',
        titleEn: '3.4 Takeaway?',
        contentZh: [
          { type: 'text', text: '这篇并没有升维到哲学层面，而是不断降维变成自己熟悉的东西，来方便理解看似陌生的事物' },
          { type: 'text', text: '我认为两种方向都非常重要' },
          { type: 'text', text: '一方是回归自我的人生哲思，另一方是回归熟悉的本质之思' },
          { type: 'text', text: '就像这简简单单的一条公式' },
          { type: 'text', text: '让我发现自己反应还不够快…最优角度θ本就应该可以由两个自定义的方向来算出' },
          { type: 'text', text: '也让我对倒数平方有了新的理解' },
          { type: 'quote', text: '更重要的是，这样理解后，它将成为我的永久记忆而非应试教育的累赘..' },
        ],
        contentEn: [
          { type: 'text', text: "This piece didn't go up to the philosophical level — instead it kept going down, turning things into familiar ground, to make sense of something that looked foreign" },
          { type: 'text', text: 'I think both directions matter' },
          { type: 'text', text: 'One is philosophical self-reflection, the other is returning to familiar essence' },
          { type: 'text', text: 'Just from this one simple formula' },
          { type: 'text', text: "I realized I wasn't quick enough… the optimal angle θ should obviously be computable from two self-defined directions" },
          { type: 'text', text: 'And I got a new understanding of reciprocal squares' },
          { type: 'quote', text: "More importantly: once you understand it this way, it becomes a permanent memory rather than another exam-crammed formula.." },
        ],
      },
    ],
  },
  {
    id: 'lda-1',
    date: '2025.12',
    tags: ['线代杂谈'],
    titleZh: '线性变化 — 零空间 — 奇异性',
    titleEn: 'Linear Maps — Null Space — Singularity',
    summaryZh: '矩阵不是在"作用"，而是在"选择性失明"。零空间不是被消掉的东西，而是等价类的生成器',
    summaryEn: 'A matrix doesn\'t "act" — it selectively ignores. The null space isn\'t what gets erased — it\'s the generator of equivalence classes',
    sections: [
      {
        titleZh: '1.1 线性变换不是"作用"，而是"选择性失明"',
        titleEn: '1.1 Linear maps don\'t "act" — they selectively ignore',
        contentZh: [
          { type: 'text',  text: '矩阵 A 只保留它能看到的方向，其余全部压成 0' },
          { type: 'text',  text: '因此 AB = A 的本质不是"B 被约束"，而是：只要 B 的改动落在 A 看不见的方向上，就等价于没发生' },
          { type: 'quote', text: '类比：一个只看黑白的相机，颜色怎么变都一样' },
        ],
        contentEn: [
          { type: 'text',  text: 'Matrix A only preserves the directions it can "see" — everything else collapses to 0' },
          { type: 'text',  text: 'So AB = A doesn\'t mean "B is constrained" — it means: as long as B\'s change lies in a direction A cannot see, nothing happened' },
          { type: 'quote', text: 'Analogy: a camera that only sees black and white — colors can change all they want' },
        ],
      },
      {
        titleZh: '1.2 零空间不是"被消掉的东西"，而是"等价类的生成器"',
        titleEn: '1.2 The null space isn\'t what gets erased — it generates equivalence classes',
        contentZh: [
          { type: 'math',  text: 'x \\sim x + z,\\quad z \\in \\operatorname{Null}(A)' },
          { type: 'text',  text: '这意味着：A 定义的不是一个映射，而是一种"等价关系"' },
          { type: 'text',  text: '所有相差一个零空间向量的输入，在 A 看来是同一个点' },
          { type: 'quote', text: '所以问题从"解一个方程"变成：在一个等价类里选一个代表' },
          { type: 'text',  text: '这才是所有"建模 / 还原 / 生成"的本质难点' },
        ],
        contentEn: [
          { type: 'math',  text: 'x \\sim x + z,\\quad z \\in \\operatorname{Null}(A)' },
          { type: 'text',  text: 'This means: A doesn\'t define a mapping — it defines an equivalence relation' },
          { type: 'text',  text: 'All inputs that differ by a null space vector look identical to A' },
          { type: 'quote', text: 'The problem shifts from "solve an equation" to: pick a representative from an equivalence class' },
          { type: 'text',  text: 'That\'s the fundamental difficulty in all modeling / reconstruction / generation' },
        ],
      },
      {
        titleZh: '1.3 解结构 = 约束 + 自由度',
        titleEn: '1.3 Solution structure = constraint + degrees of freedom',
        contentZh: [
          { type: 'text',  text: '欠定系统的通解结构是固定的：' },
          { type: 'math',  text: 'x = x_0 + z,\\quad z \\in \\operatorname{Null}(A)' },
          { type: 'text',  text: '约束只决定 x₀，真正的选择发生在 z' },
          { type: 'text',  text: '联想：拉格朗日乘子法' },
          { type: 'math',  text: '\\nabla f(x) + \\sum_i \\lambda_i \\nabla g_i(x) = 0' },
          { type: 'math',  text: 'g_i(x) = 0' },
        ],
        contentEn: [
          { type: 'text',  text: 'The general solution of an underdetermined system is fixed:' },
          { type: 'math',  text: 'x = x_0 + z,\\quad z \\in \\operatorname{Null}(A)' },
          { type: 'text',  text: 'The constraint only pins down x₀ — the real choice happens in z' },
          { type: 'text',  text: 'Think of it like Lagrange multipliers:' },
          { type: 'math',  text: '\\nabla f(x) + \\sum_i \\lambda_i \\nabla g_i(x) = 0' },
          { type: 'math',  text: 'g_i(x) = 0' },
        ],
      },
      {
        titleZh: '1.4 奇异性是降维，更是"信息的不可区分性"',
        titleEn: '1.4 Singularity is dimension loss — more precisely, indistinguishability',
        contentZh: [
          { type: 'text',    text: '常见说法是"降维"，但我认为更精确的是：' },
          { type: 'quote',   text: '系统主动让不同状态变得不可区分，强制合并' },
          { type: 'bullets', items: ['投影会丢信息', '共线性会导致不稳定', '逆问题会出现无限解'] },
          { type: 'quote',   text: '本质是区分能力被破坏，而不是表达能力不足' },
          { type: 'text',    text: '但这对反向构建升维系统何尝不是一种机遇呢？' },
        ],
        contentEn: [
          { type: 'text',    text: 'The common framing is "dimension reduction" — but more precisely:' },
          { type: 'quote',   text: 'The system actively makes different states indistinguishable, forcing them to merge' },
          { type: 'bullets', items: ['Projection loses information', 'Collinearity causes instability', 'Inverse problems have infinite solutions'] },
          { type: 'quote',   text: 'The essence is a breakdown in distinguishing ability — not a lack of expressive capacity' },
          { type: 'text',    text: "But isn't this exactly an opportunity for building systems that elevate dimensions?" },
        ],
      },
    ],
  },
  {
    id: 'lda-2',
    date: '2025.12',
    tags: ['线代杂谈'],
    titleZh: '叉积 — 幻觉 — 自由度 — 人生',
    titleEn: 'Cross Product — Hallucination — Degrees of Freedom — Life',
    summaryZh: '叉积不是被发现的，而是被构造的。高维空间几乎处处正交。幻觉是在没有约束的地方做最优延拓',
    summaryEn: "The cross product wasn't discovered — it was constructed. High-dimensional space is almost everywhere orthogonal. Hallucination is optimal extrapolation in unconstrained regions",
    sections: [
      {
        titleZh: '2.1 叉积来源：把面伪装成向量',
        titleEn: '2.1 Cross product: disguising a surface as a vector',
        contentZh: [
          { type: 'text',    text: '叉积不是被发现的，而是被"构造"的：' },
          { type: 'math',    text: '\\mathbf{a} \\times \\mathbf{b} = (S_{yz},\\, S_{zx},\\, S_{xy})' },
          { type: 'quote',   text: '面的信息（面积 + 朝向）可以被编码成一个向量对象' },
          { type: 'text',    text: '这是一种典型操作：用已有结构（向量）去承载更复杂的对象（面）' },
          { type: 'bullets', items: ['行列式 → 体积', 'Jacobian → 局部变形', 'Embedding → 语义'] },
        ],
        contentEn: [
          { type: 'text',    text: "The cross product wasn't discovered — it was constructed:" },
          { type: 'math',    text: '\\mathbf{a} \\times \\mathbf{b} = (S_{yz},\\, S_{zx},\\, S_{xy})' },
          { type: 'quote',   text: 'Surface information (area + orientation) can be encoded as a vector object' },
          { type: 'text',    text: 'This is a recurring pattern: using an existing structure (vectors) to carry a more complex object (surfaces)' },
          { type: 'bullets', items: ['Determinant → volume', 'Jacobian → local deformation', 'Embedding → semantics'] },
        ],
      },
      {
        titleZh: '2.2 高维空间"不大"反而"几乎处处正交"',
        titleEn: "2.2 High-dimensional space isn't \"big\" — it's almost everywhere orthogonal",
        contentZh: [
          { type: 'quote', text: '随便取两个向量，几乎都是互相正交的' },
          { type: 'text',  text: '这带来一个重要后果：系统天然拥有大量"互不干扰的存储通道"' },
          { type: 'text',  text: 'LLM 的能力不是来自"记住更多"，而是：能把不同语义放进彼此几乎不干扰的方向' },
        ],
        contentEn: [
          { type: 'quote', text: "Any two random vectors in high dimensions are almost orthogonal" },
          { type: 'text',  text: 'The system naturally has a huge number of "non-interfering storage channels"' },
          { type: 'text',  text: 'LLM capability doesn\'t come from "remembering more" — it comes from placing different semantics into directions that barely interfere with each other' },
        ],
      },
      {
        titleZh: '2.3 推理不是线性延伸，而是在"约束流形"上行走',
        titleEn: "2.3 Reasoning isn't linear extension — it's walking on a constraint manifold",
        contentZh: [
          { type: 'quote',   text: '每一步都在重新投影到一个高维约束面上' },
          { type: 'text',    text: '这些约束来自：' },
          { type: 'bullets', items: ['语法结构', '上下文', 'attention'] },
          { type: 'text',    text: '因此"逻辑通顺"的来源是：始终没有离开那个流形' },
          { type: 'text',    text: '而它不一定"理解了真理"？' },
        ],
        contentEn: [
          { type: 'quote',   text: 'Each step is a re-projection onto a high-dimensional constraint surface' },
          { type: 'text',    text: 'These constraints come from:' },
          { type: 'bullets', items: ['Grammar structure', 'Context', 'Attention'] },
          { type: 'text',    text: 'So "logical coherence" means: never leaving that manifold' },
          { type: 'text',    text: 'But that doesn\'t mean it "understands truth"' },
        ],
      },
      {
        titleZh: '2.4 幻觉不是错误，而是"在没有约束的地方做最优延拓"',
        titleEn: "2.4 Hallucination isn't an error — it's optimal extrapolation in unconstrained space",
        contentZh: [
          { type: 'quote', text: '在已有结构上做最平滑的延伸，在错误流形上的最优解' },
          { type: 'text',  text: '问题在于：这个延伸可能完全偏离真实世界' },
          { type: 'text',  text: '这和逆问题似乎一致：解不唯一时，系统一定会引入某种隐含偏好' },
        ],
        contentEn: [
          { type: 'quote', text: 'The optimal solution on the wrong manifold — smoothest possible extension from existing structure' },
          { type: 'text',  text: 'The problem: this extension may deviate entirely from the real world' },
          { type: 'text',  text: 'This mirrors inverse problems: when solutions are not unique, the system always introduces some hidden preference' },
        ],
      },
      {
        titleZh: '2.5 真正的自由度存在于"观测不到的地方"',
        titleEn: "2.5 Real degrees of freedom live where observation can't reach",
        contentZh: [
          { type: 'quote',   text: '系统的自由度，只存在于它无法约束的方向上' },
          { type: 'bullets', items: ['零空间 → 数学上的自由度', '高维正交 → 表达上的自由度', '幻觉 → 认知上的自由度'] },
          { type: 'text',    text: '而所有"能力"，似乎都是：如何在这些自由度中施加结构/限制？' },
        ],
        contentEn: [
          { type: 'quote',   text: "A system's degrees of freedom exist only in the directions it cannot constrain" },
          { type: 'bullets', items: ['Null space → mathematical degrees of freedom', 'High-dim orthogonality → expressive degrees of freedom', 'Hallucination → cognitive degrees of freedom'] },
          { type: 'text',    text: 'And all "capability" seems to be: how do you impose structure within these degrees of freedom?' },
        ],
      },
      {
        titleZh: '2.6 人生',
        titleEn: '2.6 Life',
        contentZh: [
          { type: 'text',  text: '如果人生是系统…有这么庞大的自由度' },
          { type: 'text',  text: '为什么要批评/懊悔困于之前约束的自己做出的决定？' },
          { type: 'text',  text: '为什么要逼迫自己在高压环境下短时间内定好方向？' },
          { type: 'quote', text: '或许不断修正限制地随心所欲地终身学习才是我想追求的..?' },
        ],
        contentEn: [
          { type: 'text',  text: 'If life is a system… with this many degrees of freedom' },
          { type: 'text',  text: 'Why criticize or regret the decisions made by a past self constrained by different limits?' },
          { type: 'text',  text: 'Why force yourself to lock in a direction under pressure in a short window?' },
          { type: 'quote', text: 'Maybe what I actually want is: lifelong learning, following curiosity, revising constraints as I go..?' },
        ],
      },
    ],
  },
];